version: 2
updates:
  - package-ecosystem: composer
    directory: /SkinCare
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    labels:
      - dependencies
    groups:
      laravel-dependencies:
        patterns:
          - "illuminate/*"
          - "laravel/*"

  - package-ecosystem: npm
    directory: /e2e
    schedule:
      interval: weekly
      day: monday
      time: "05:15"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    labels:
      - dependencies
